FROM nginx:1.11.9 
MAINTAINER Ed & Magdalena 
EXPOSE 8080
RUN builddate=$(date)
#COPY nginx.conf /etc/nginx/
#RUN groupadd -r nginxuser
#RUN useradd -r -g nginxuser nginxuser
#USER nginx
#RUN /etc/init.d/nginx start 
#ENTRYPOINT ["echo Running!"]

